add_newline = false

[character]
success_symbol = '[ ğŸ¼ ]()'

[aws]
disabled = true

[cmd_duration]
disabled = true

[conda]
format = '[$symbol$environment]($style)'
symbol =  'ğŸ…’  '

[line_break]
disabled = true

[nodejs]
disabled = true

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
version_format = "${raw}"

[terraform]
format = "[ğŸğŸ’¨ $version$workspace]($style) "
