add_newline = false

[aws]
disabled = true

[character]
success_symbol = '[ ğŸ¼ ]()'

[cmd_duration]
disabled = true

[conda]
format = '[$symbol$environment]($style)'
symbol =  'ğŸ…’  '

[hostname]
ssh_only = true
format = '[ğŸ§Œ   BEAST ğŸ§Œ   ](bold red)'
disabled = false

[line_break]
disabled = true

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
version_format = "${raw}"

[terraform]
format = "[ğŸğŸ’¨ $version$workspace]($style) "

[time]
disabled = false
format = 'â°[ $time ](bold blue)'
time_format = '%R'
